In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import fpgrowth, association_rules, apriori

plt.style.use("ggplot")

In [2]:
category_tree = pd.read_csv("data/ecommerce-dataset/category_tree.csv")
events = pd.read_csv("data/ecommerce-dataset/events.csv")
item_properties_part1 = pd.read_csv("data/ecommerce-dataset/item_properties_part1.csv")
item_properties_part2 = pd.read_csv("data/ecommerce-dataset/item_properties_part2.csv")

In [3]:
display(category_tree.head(10))
display(events.head(10))
display(item_properties_part1.head(10))
display(item_properties_part2.head(10))

   categoryid  parentid
0        1016     213.0
1         809     169.0
2         570       9.0
3        1691     885.0
4         536    1691.0
5         231       NaN
6         542     378.0
7        1146     542.0
8        1140     542.0
9        1479    1537.0

       timestamp  visitorid event  itemid  transactionid
0  1433221332117     257597  view  355908            NaN
1  1433224214164     992329  view  248676            NaN
2  1433221999827     111016  view  318965            NaN
3  1433221955914     483717  view  253185            NaN
4  1433221337106     951259  view  367447            NaN
5  1433224086234     972639  view   22556            NaN
6  1433221923240     810725  view  443030            NaN
7  1433223291897     794181  view  439202            NaN
8  1433220899221     824915  view  428805            NaN
9  1433221204592     339335  view   82389            NaN

       timestamp  itemid    property                            value
0  1435460400000  460429  categoryid                             1338
1  1441508400000  206783         888          1116713 960601 n277.200
2  1439089200000  395014         400  n552.000 639502 n720.000 424566
3  1431226800000   59481         790                       n15360.000
4  1431831600000  156781         917                           828513
5  1436065200000  285026   available                                0
6  1434250800000   89534         213                          1121373
7  1431831600000  264312           6                           319724
8  1433646000000  229370         202                          1330310
9  1434250800000   98113         451                  1141052 n48.000

,timestamp,itemid,property,value
0,1433041200000,183478,561,769062
1,1439694000000,132256,976,n26.400 1135780
2,1435460400000,420307,921,1149317 1257525
3,1431831600000,403324,917,1204143
4,1435460400000,230701,521,769062
5,1433041200000,286407,202,820407
6,1438484400000,256368,888,437265 1296497 n24.000 229949 651738 285933
7,1437879600000,307534,888,150169 212349 1095303 824508 1257235 153900
8,1439089200000,102767,888,5135 790941 1055803 221748 122132 n12.000 1135...
9,1431831600000,215180,71,1096621

In [4]:
df_transaction = events[events["transactionid"].notna()]
df_transaction

             timestamp  visitorid        event  itemid  transactionid
130      1433222276276     599528  transaction  356475         4000.0
304      1433193500981     121688  transaction   15335        11117.0
418      1433193915008     552148  transaction   81345         5444.0
814      1433176736375     102019  transaction  150318        13556.0
843      1433174518180     189384  transaction  310791         7244.0
...                ...        ...          ...     ...            ...
2755294  1438377176570    1050575  transaction   31640         8354.0
2755349  1438379878779     861299  transaction  456602         3643.0
2755508  1438357730123     855941  transaction  235771         4385.0
2755603  1438355560300     548772  transaction   29167        13872.0
2755607  1438358989163    1051054  transaction  312728        17579.0

[22457 rows x 5 columns]

In [27]:
basket = df_transaction.groupby("transactionid")["itemid"].apply(list)
basket = basket[basket.apply(len) > 1]
basket

transactionid
12.0                       [239235, 432742]
23.0         [351124, 397642, 93556, 57548]
27.0       [272976, 130226, 288078, 272770]
28.0        [127123, 213834, 31830, 195958]
37.0                       [370745, 192990]
                         ...
17657.0                     [62616, 283896]
17660.0            [114070, 265920, 157743]
17662.0                    [100586, 442610]
17663.0                    [334401, 180349]
17669.0                    [132418, 260256]
Name: itemid, Length: 2710, dtype: object

In [28]:
te = TransactionEncoder()
te_data = te.fit_transform(basket)

df_te = pd.DataFrame(te_data, columns=te.columns_)

In [29]:
df_te

,15,19,25,42,147,212,496,546,563,651,...,465922,465951,466109,466114,466161,466319,466321,466443,466603,466710
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2705,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2706,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2707,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2708,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2709,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [32]:
freq_apriori = apriori(df_te, min_support=0.001, use_colnames=True)
freq_fpgrowth = fpgrowth(df_te, min_support=0.001, use_colnames=True)

rules_apriori = association_rules(freq_apriori, metric="lift", min_threshold=1.2)
rules_fpgrowth = association_rules(freq_fpgrowth, metric="lift", min_threshold=1.2)

In [34]:
rules_apriori

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({146642}),frozenset({10572}),0.001107,0.006273,0.001107,1.000000,159.411765,1.0,0.001100,inf,0.994828,0.176471,1.000000,0.588235
1,frozenset({10572}),frozenset({146642}),0.006273,0.001107,0.001107,0.176471,159.411765,1.0,0.001100,1.212941,1.000000,0.176471,0.175558,0.588235
2,frozenset({10572}),frozenset({333039}),0.006273,0.001107,0.001107,0.176471,159.411765,1.0,0.001100,1.212941,1.000000,0.176471,0.175558,0.588235
3,frozenset({333039}),frozenset({10572}),0.001107,0.006273,0.001107,1.000000,159.411765,1.0,0.001100,inf,0.994828,0.176471,1.000000,0.588235
4,frozenset({10572}),frozenset({341869}),0.006273,0.001107,0.001107,0.176471,159.411765,1.0,0.001100,1.212941,1.000000,0.176471,0.175558,0.588235
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,frozenset({10572}),"frozenset({357529, 146642, 382130, 341869})",0.006273,0.001107,0.001107,0.176471,159.411765,1.0,0.001100,1.212941,1.000000,0.176471,0.175558,0.588235
412,frozenset({341869}),"frozenset({357529, 146642, 382130, 10572})",0.001107,0.001107,0.001107,1.000000,903.333333,1.0,0.001106,inf,1.000000,1.000000,1.000000,1.000000
413,frozenset({382130}),"frozenset({357529, 146642, 10572, 341869})",0.002214,0.001107,0.001107,0.500000,451.666667,1.0,0.001105,1.997786,1.000000,0.500000,0.499446,0.750000
414,frozenset({146642}),"frozenset({357529, 382130, 10572, 341869})",0.001107,0.001107,0.001107,1.000000,903.333333,1.0,0.001106,inf,1.000000,1.000000,1.000000,1.000000
415,frozenset({357529}),"frozenset({146642, 382130, 10572, 341869})",0.001845,0.001107,0.001107,0.600000,542.000000,1.0,0.001105,2.497232,1.000000,0.600000,0.599557,0.800000

In [35]:
rules_fpgrowth

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({382130}),frozenset({10572}),0.002214,0.006273,0.001107,0.500000,79.705882,1.0,0.001093,1.987454,0.989645,0.150000,0.496844,0.338235
1,frozenset({10572}),frozenset({382130}),0.006273,0.002214,0.001107,0.176471,79.705882,1.0,0.001093,1.211597,0.993687,0.150000,0.174643,0.338235
2,frozenset({379520}),frozenset({432171}),0.002214,0.001845,0.001845,0.833333,451.666667,1.0,0.001841,5.988930,1.000000,0.833333,0.833025,0.916667
3,frozenset({432171}),frozenset({379520}),0.001845,0.002214,0.001845,1.000000,451.666667,1.0,0.001841,inf,0.999630,0.833333,1.000000,0.916667
4,frozenset({432171}),frozenset({269773}),0.001845,0.001476,0.001476,0.800000,542.000000,1.0,0.001473,4.992620,1.000000,0.800000,0.799704,0.900000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
411,"frozenset({387504, 390167})",frozenset({167827}),0.001107,0.001107,0.001107,1.000000,903.333333,1.0,0.001106,inf,1.000000,1.000000,1.000000,1.000000
412,"frozenset({167827, 390167})",frozenset({387504}),0.001107,0.001107,0.001107,1.000000,903.333333,1.0,0.001106,inf,1.000000,1.000000,1.000000,1.000000
413,frozenset({387504}),"frozenset({167827, 390167})",0.001107,0.001107,0.001107,1.000000,903.333333,1.0,0.001106,inf,1.000000,1.000000,1.000000,1.000000
414,frozenset({167827}),"frozenset({387504, 390167})",0.001107,0.001107,0.001107,1.000000,903.333333,1.0,0.001106,inf,1.000000,1.000000,1.000000,1.000000
415,frozenset({390167}),"frozenset({387504, 167827})",0.001107,0.001107,0.001107,1.000000,903.333333,1.0,0.001106,inf,1.000000,1.000000,1.000000,1.000000